-- Do not edit, this file was autogenerated by generate-halogen-css-modules
module Demo.Pages.Ripple.Css (styles) where

import Halogen.HTML (ClassName)

foreign import styles ::
  { demoBox :: ClassName
  }
