-- Do not edit, this file was autogenerated by generate-halogen-css-modules
module Demo.Pages.TextField.Css (styles) where

import Halogen.HTML (ClassName)

foreign import styles ::
  { textFieldContainerHero :: ClassName
  , textFieldContainerHeroRoot :: ClassName
  , textFieldContainer :: ClassName
  , textFieldRowFullwidth :: ClassName
  , textFieldRow :: ClassName
  }
