-- Do not edit, this file was autogenerated by generate-halogen-css-modules
module Demo.Pages.Button.Css (styles) where

import Halogen.HTML (ClassName)

foreign import styles ::
  { my_button_dense :: ClassName
  , heroMargin :: ClassName
  , rowMargin :: ClassName
  , shapedButtons :: ClassName
  }
