-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.DataTable (mdc_checkbox____anim_checked_unchecked, mdc_checkbox____anim_indeterminate_unchecked, mdc_checkbox____anim_unchecked_checked, mdc_checkbox____anim_unchecked_indeterminate, mdc_checkbox____selected, mdc_checkbox__background, mdc_checkbox__native_control, mdc_checkbox__ripple, mdc_data_table, mdc_data_table__cell, mdc_data_table__cell____checkbox, mdc_data_table__cell____numeric, mdc_data_table__content, mdc_data_table__header_cell, mdc_data_table__header_cell____checkbox, mdc_data_table__header_cell____numeric, mdc_data_table__header_row, mdc_data_table__header_row_checkbox, mdc_data_table__row, mdc_data_table__row____selected, mdc_data_table__row_checkbox, mdc_data_table__table, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused) where

import Halogen.HTML (ClassName(..))

mdc_checkbox____anim_checked_unchecked :: ClassName
mdc_checkbox____anim_checked_unchecked = ClassName "mdc-checkbox--anim-checked-unchecked"

mdc_checkbox____anim_indeterminate_unchecked :: ClassName
mdc_checkbox____anim_indeterminate_unchecked = ClassName "mdc-checkbox--anim-indeterminate-unchecked"

mdc_checkbox____anim_unchecked_checked :: ClassName
mdc_checkbox____anim_unchecked_checked = ClassName "mdc-checkbox--anim-unchecked-checked"

mdc_checkbox____anim_unchecked_indeterminate :: ClassName
mdc_checkbox____anim_unchecked_indeterminate = ClassName "mdc-checkbox--anim-unchecked-indeterminate"

mdc_checkbox____selected :: ClassName
mdc_checkbox____selected = ClassName "mdc-checkbox--selected"

mdc_checkbox__background :: ClassName
mdc_checkbox__background = ClassName "mdc-checkbox__background"

mdc_checkbox__native_control :: ClassName
mdc_checkbox__native_control = ClassName "mdc-checkbox__native-control"

mdc_checkbox__ripple :: ClassName
mdc_checkbox__ripple = ClassName "mdc-checkbox__ripple"

mdc_data_table :: ClassName
mdc_data_table = ClassName "mdc-data-table"

mdc_data_table__cell :: ClassName
mdc_data_table__cell = ClassName "mdc-data-table__cell"

mdc_data_table__cell____checkbox :: ClassName
mdc_data_table__cell____checkbox = ClassName "mdc-data-table__cell--checkbox"

mdc_data_table__cell____numeric :: ClassName
mdc_data_table__cell____numeric = ClassName "mdc-data-table__cell--numeric"

mdc_data_table__content :: ClassName
mdc_data_table__content = ClassName "mdc-data-table__content"

mdc_data_table__header_cell :: ClassName
mdc_data_table__header_cell = ClassName "mdc-data-table__header-cell"

mdc_data_table__header_cell____checkbox :: ClassName
mdc_data_table__header_cell____checkbox = ClassName "mdc-data-table__header-cell--checkbox"

mdc_data_table__header_cell____numeric :: ClassName
mdc_data_table__header_cell____numeric = ClassName "mdc-data-table__header-cell--numeric"

mdc_data_table__header_row :: ClassName
mdc_data_table__header_row = ClassName "mdc-data-table__header-row"

mdc_data_table__header_row_checkbox :: ClassName
mdc_data_table__header_row_checkbox = ClassName "mdc-data-table__header-row-checkbox"

mdc_data_table__row :: ClassName
mdc_data_table__row = ClassName "mdc-data-table__row"

mdc_data_table__row____selected :: ClassName
mdc_data_table__row____selected = ClassName "mdc-data-table__row--selected"

mdc_data_table__row_checkbox :: ClassName
mdc_data_table__row_checkbox = ClassName "mdc-data-table__row-checkbox"

mdc_data_table__table :: ClassName
mdc_data_table__table = ClassName "mdc-data-table__table"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

