-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.DataTable (mdc_button__icon, mdc_checkbox____anim_checked_unchecked, mdc_checkbox____anim_indeterminate_unchecked, mdc_checkbox____anim_unchecked_checked, mdc_checkbox____anim_unchecked_indeterminate, mdc_checkbox____selected, mdc_checkbox__background, mdc_checkbox__native_control, mdc_checkbox__ripple, mdc_data_table, mdc_data_table____in_progress, mdc_data_table__cell, mdc_data_table__cell____checkbox, mdc_data_table__cell____numeric, mdc_data_table__content, mdc_data_table__header_cell, mdc_data_table__header_cell____checkbox, mdc_data_table__header_cell____numeric, mdc_data_table__header_cell____sorted, mdc_data_table__header_cell____sorted_descending, mdc_data_table__header_cell____with_sort, mdc_data_table__header_cell_wrapper, mdc_data_table__header_row, mdc_data_table__header_row_checkbox, mdc_data_table__pagination, mdc_data_table__pagination_button, mdc_data_table__pagination_navigation, mdc_data_table__pagination_rows_per_page, mdc_data_table__pagination_rows_per_page_label, mdc_data_table__pagination_rows_per_page_select, mdc_data_table__pagination_total, mdc_data_table__pagination_trailing, mdc_data_table__progress_indicator, mdc_data_table__row, mdc_data_table__row____selected, mdc_data_table__row_checkbox, mdc_data_table__scrim, mdc_data_table__sort_icon_button, mdc_data_table__sort_status_label, mdc_data_table__table, mdc_data_table__table_container, mdc_floating_label____float_above, mdc_floating_label____shake, mdc_list_item, mdc_notched_outline____upgraded, mdc_notched_outline__leading, mdc_notched_outline__notch, mdc_notched_outline__trailing, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_select____disabled, mdc_select____outlined, mdc_select__anchor, mdc_select__dropdown_icon) where

import Halogen.HTML (ClassName(..))

mdc_button__icon :: ClassName
mdc_button__icon = ClassName "mdc-button__icon"

mdc_checkbox____anim_checked_unchecked :: ClassName
mdc_checkbox____anim_checked_unchecked = ClassName "mdc-checkbox--anim-checked-unchecked"

mdc_checkbox____anim_indeterminate_unchecked :: ClassName
mdc_checkbox____anim_indeterminate_unchecked = ClassName "mdc-checkbox--anim-indeterminate-unchecked"

mdc_checkbox____anim_unchecked_checked :: ClassName
mdc_checkbox____anim_unchecked_checked = ClassName "mdc-checkbox--anim-unchecked-checked"

mdc_checkbox____anim_unchecked_indeterminate :: ClassName
mdc_checkbox____anim_unchecked_indeterminate = ClassName "mdc-checkbox--anim-unchecked-indeterminate"

mdc_checkbox____selected :: ClassName
mdc_checkbox____selected = ClassName "mdc-checkbox--selected"

mdc_checkbox__background :: ClassName
mdc_checkbox__background = ClassName "mdc-checkbox__background"

mdc_checkbox__native_control :: ClassName
mdc_checkbox__native_control = ClassName "mdc-checkbox__native-control"

mdc_checkbox__ripple :: ClassName
mdc_checkbox__ripple = ClassName "mdc-checkbox__ripple"

mdc_data_table :: ClassName
mdc_data_table = ClassName "mdc-data-table"

mdc_data_table____in_progress :: ClassName
mdc_data_table____in_progress = ClassName "mdc-data-table--in-progress"

mdc_data_table__cell :: ClassName
mdc_data_table__cell = ClassName "mdc-data-table__cell"

mdc_data_table__cell____checkbox :: ClassName
mdc_data_table__cell____checkbox = ClassName "mdc-data-table__cell--checkbox"

mdc_data_table__cell____numeric :: ClassName
mdc_data_table__cell____numeric = ClassName "mdc-data-table__cell--numeric"

mdc_data_table__content :: ClassName
mdc_data_table__content = ClassName "mdc-data-table__content"

mdc_data_table__header_cell :: ClassName
mdc_data_table__header_cell = ClassName "mdc-data-table__header-cell"

mdc_data_table__header_cell____checkbox :: ClassName
mdc_data_table__header_cell____checkbox = ClassName "mdc-data-table__header-cell--checkbox"

mdc_data_table__header_cell____numeric :: ClassName
mdc_data_table__header_cell____numeric = ClassName "mdc-data-table__header-cell--numeric"

mdc_data_table__header_cell____sorted :: ClassName
mdc_data_table__header_cell____sorted = ClassName "mdc-data-table__header-cell--sorted"

mdc_data_table__header_cell____sorted_descending :: ClassName
mdc_data_table__header_cell____sorted_descending = ClassName "mdc-data-table__header-cell--sorted-descending"

mdc_data_table__header_cell____with_sort :: ClassName
mdc_data_table__header_cell____with_sort = ClassName "mdc-data-table__header-cell--with-sort"

mdc_data_table__header_cell_wrapper :: ClassName
mdc_data_table__header_cell_wrapper = ClassName "mdc-data-table__header-cell-wrapper"

mdc_data_table__header_row :: ClassName
mdc_data_table__header_row = ClassName "mdc-data-table__header-row"

mdc_data_table__header_row_checkbox :: ClassName
mdc_data_table__header_row_checkbox = ClassName "mdc-data-table__header-row-checkbox"

mdc_data_table__pagination :: ClassName
mdc_data_table__pagination = ClassName "mdc-data-table__pagination"

mdc_data_table__pagination_button :: ClassName
mdc_data_table__pagination_button = ClassName "mdc-data-table__pagination-button"

mdc_data_table__pagination_navigation :: ClassName
mdc_data_table__pagination_navigation = ClassName "mdc-data-table__pagination-navigation"

mdc_data_table__pagination_rows_per_page :: ClassName
mdc_data_table__pagination_rows_per_page = ClassName "mdc-data-table__pagination-rows-per-page"

mdc_data_table__pagination_rows_per_page_label :: ClassName
mdc_data_table__pagination_rows_per_page_label = ClassName "mdc-data-table__pagination-rows-per-page-label"

mdc_data_table__pagination_rows_per_page_select :: ClassName
mdc_data_table__pagination_rows_per_page_select = ClassName "mdc-data-table__pagination-rows-per-page-select"

mdc_data_table__pagination_total :: ClassName
mdc_data_table__pagination_total = ClassName "mdc-data-table__pagination-total"

mdc_data_table__pagination_trailing :: ClassName
mdc_data_table__pagination_trailing = ClassName "mdc-data-table__pagination-trailing"

mdc_data_table__progress_indicator :: ClassName
mdc_data_table__progress_indicator = ClassName "mdc-data-table__progress-indicator"

mdc_data_table__row :: ClassName
mdc_data_table__row = ClassName "mdc-data-table__row"

mdc_data_table__row____selected :: ClassName
mdc_data_table__row____selected = ClassName "mdc-data-table__row--selected"

mdc_data_table__row_checkbox :: ClassName
mdc_data_table__row_checkbox = ClassName "mdc-data-table__row-checkbox"

mdc_data_table__scrim :: ClassName
mdc_data_table__scrim = ClassName "mdc-data-table__scrim"

mdc_data_table__sort_icon_button :: ClassName
mdc_data_table__sort_icon_button = ClassName "mdc-data-table__sort-icon-button"

mdc_data_table__sort_status_label :: ClassName
mdc_data_table__sort_status_label = ClassName "mdc-data-table__sort-status-label"

mdc_data_table__table :: ClassName
mdc_data_table__table = ClassName "mdc-data-table__table"

mdc_data_table__table_container :: ClassName
mdc_data_table__table_container = ClassName "mdc-data-table__table-container"

mdc_floating_label____float_above :: ClassName
mdc_floating_label____float_above = ClassName "mdc-floating-label--float-above"

mdc_floating_label____shake :: ClassName
mdc_floating_label____shake = ClassName "mdc-floating-label--shake"

mdc_list_item :: ClassName
mdc_list_item = ClassName "mdc-list-item"

mdc_notched_outline____upgraded :: ClassName
mdc_notched_outline____upgraded = ClassName "mdc-notched-outline--upgraded"

mdc_notched_outline__leading :: ClassName
mdc_notched_outline__leading = ClassName "mdc-notched-outline__leading"

mdc_notched_outline__notch :: ClassName
mdc_notched_outline__notch = ClassName "mdc-notched-outline__notch"

mdc_notched_outline__trailing :: ClassName
mdc_notched_outline__trailing = ClassName "mdc-notched-outline__trailing"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_select____disabled :: ClassName
mdc_select____disabled = ClassName "mdc-select--disabled"

mdc_select____outlined :: ClassName
mdc_select____outlined = ClassName "mdc-select--outlined"

mdc_select__anchor :: ClassName
mdc_select__anchor = ClassName "mdc-select__anchor"

mdc_select__dropdown_icon :: ClassName
mdc_select__dropdown_icon = ClassName "mdc-select__dropdown-icon"

