-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Fab (mdc_elevation_overlay, mdc_fab, mdc_fab____exited, mdc_fab____extended, mdc_fab____mini, mdc_fab____touch, mdc_fab__icon, mdc_fab__label, mdc_fab__ripple, mdc_fab__touch, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded, mdc_touch_target_wrapper) where

import Halogen.HTML (ClassName(..))

mdc_elevation_overlay :: ClassName
mdc_elevation_overlay = ClassName "mdc-elevation-overlay"

mdc_fab :: ClassName
mdc_fab = ClassName "mdc-fab"

mdc_fab____exited :: ClassName
mdc_fab____exited = ClassName "mdc-fab--exited"

mdc_fab____extended :: ClassName
mdc_fab____extended = ClassName "mdc-fab--extended"

mdc_fab____mini :: ClassName
mdc_fab____mini = ClassName "mdc-fab--mini"

mdc_fab____touch :: ClassName
mdc_fab____touch = ClassName "mdc-fab--touch"

mdc_fab__icon :: ClassName
mdc_fab__icon = ClassName "mdc-fab__icon"

mdc_fab__label :: ClassName
mdc_fab__label = ClassName "mdc-fab__label"

mdc_fab__ripple :: ClassName
mdc_fab__ripple = ClassName "mdc-fab__ripple"

mdc_fab__touch :: ClassName
mdc_fab__touch = ClassName "mdc-fab__touch"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"

mdc_touch_target_wrapper :: ClassName
mdc_touch_target_wrapper = ClassName "mdc-touch-target-wrapper"
