-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.IconButton (mdc_icon_button, mdc_icon_button____on, mdc_icon_button__icon, mdc_icon_button__icon____on, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded) where

import Halogen.HTML (ClassName(..))

mdc_icon_button :: ClassName
mdc_icon_button = ClassName "mdc-icon-button"

mdc_icon_button____on :: ClassName
mdc_icon_button____on = ClassName "mdc-icon-button--on"

mdc_icon_button__icon :: ClassName
mdc_icon_button__icon = ClassName "mdc-icon-button__icon"

mdc_icon_button__icon____on :: ClassName
mdc_icon_button__icon____on = ClassName "mdc-icon-button__icon--on"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"
