-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Radio (mdc_radio, mdc_radio____disabled, mdc_radio____touch, mdc_radio__background, mdc_radio__inner_circle, mdc_radio__native_control, mdc_radio__outer_circle, mdc_radio__ripple, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded, mdc_touch_target_wrapper) where

import Halogen.HTML (ClassName(..))

mdc_radio :: ClassName
mdc_radio = ClassName "mdc-radio"

mdc_radio____disabled :: ClassName
mdc_radio____disabled = ClassName "mdc-radio--disabled"

mdc_radio____touch :: ClassName
mdc_radio____touch = ClassName "mdc-radio--touch"

mdc_radio__background :: ClassName
mdc_radio__background = ClassName "mdc-radio__background"

mdc_radio__inner_circle :: ClassName
mdc_radio__inner_circle = ClassName "mdc-radio__inner-circle"

mdc_radio__native_control :: ClassName
mdc_radio__native_control = ClassName "mdc-radio__native-control"

mdc_radio__outer_circle :: ClassName
mdc_radio__outer_circle = ClassName "mdc-radio__outer-circle"

mdc_radio__ripple :: ClassName
mdc_radio__ripple = ClassName "mdc-radio__ripple"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"

mdc_touch_target_wrapper :: ClassName
mdc_touch_target_wrapper = ClassName "mdc-touch-target-wrapper"
