-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Ripple (mdc_ripple_surface, mdc_ripple_surface____accent, mdc_ripple_surface____primary, mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded) where

import Halogen.HTML (ClassName(..))

mdc_ripple_surface :: ClassName
mdc_ripple_surface = ClassName "mdc-ripple-surface"

mdc_ripple_surface____accent :: ClassName
mdc_ripple_surface____accent = ClassName "mdc-ripple-surface--accent"

mdc_ripple_surface____primary :: ClassName
mdc_ripple_surface____primary = ClassName "mdc-ripple-surface--primary"

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"
