-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Switch (mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded, mdc_switch, mdc_switch____checked, mdc_switch____disabled, mdc_switch__native_control, mdc_switch__thumb, mdc_switch__thumb_underlay, mdc_switch__track) where

import Halogen.HTML (ClassName(..))

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"

mdc_switch :: ClassName
mdc_switch = ClassName "mdc-switch"

mdc_switch____checked :: ClassName
mdc_switch____checked = ClassName "mdc-switch--checked"

mdc_switch____disabled :: ClassName
mdc_switch____disabled = ClassName "mdc-switch--disabled"

mdc_switch__native_control :: ClassName
mdc_switch__native_control = ClassName "mdc-switch__native-control"

mdc_switch__thumb :: ClassName
mdc_switch__thumb = ClassName "mdc-switch__thumb"

mdc_switch__thumb_underlay :: ClassName
mdc_switch__thumb_underlay = ClassName "mdc-switch__thumb-underlay"

mdc_switch__track :: ClassName
mdc_switch__track = ClassName "mdc-switch__track"

