-- Do not edit, this file was autogenerated by generate-halogen-generate-css-classes
module Material.Classes.Tab (mdc_ripple_upgraded, mdc_ripple_upgraded____background_focused, mdc_ripple_upgraded____foreground_activation, mdc_ripple_upgraded____foreground_deactivation, mdc_ripple_upgraded____unbounded, mdc_tab, mdc_tab____active, mdc_tab____min_width, mdc_tab____stacked, mdc_tab__content, mdc_tab__icon, mdc_tab__ripple, mdc_tab__text_label) where

import Halogen.HTML (ClassName(..))

mdc_ripple_upgraded :: ClassName
mdc_ripple_upgraded = ClassName "mdc-ripple-upgraded"

mdc_ripple_upgraded____background_focused :: ClassName
mdc_ripple_upgraded____background_focused = ClassName "mdc-ripple-upgraded--background-focused"

mdc_ripple_upgraded____foreground_activation :: ClassName
mdc_ripple_upgraded____foreground_activation = ClassName "mdc-ripple-upgraded--foreground-activation"

mdc_ripple_upgraded____foreground_deactivation :: ClassName
mdc_ripple_upgraded____foreground_deactivation = ClassName "mdc-ripple-upgraded--foreground-deactivation"

mdc_ripple_upgraded____unbounded :: ClassName
mdc_ripple_upgraded____unbounded = ClassName "mdc-ripple-upgraded--unbounded"

mdc_tab :: ClassName
mdc_tab = ClassName "mdc-tab"

mdc_tab____active :: ClassName
mdc_tab____active = ClassName "mdc-tab--active"

mdc_tab____min_width :: ClassName
mdc_tab____min_width = ClassName "mdc-tab--min-width"

mdc_tab____stacked :: ClassName
mdc_tab____stacked = ClassName "mdc-tab--stacked"

mdc_tab__content :: ClassName
mdc_tab__content = ClassName "mdc-tab__content"

mdc_tab__icon :: ClassName
mdc_tab__icon = ClassName "mdc-tab__icon"

mdc_tab__ripple :: ClassName
mdc_tab__ripple = ClassName "mdc-tab__ripple"

mdc_tab__text_label :: ClassName
mdc_tab__text_label = ClassName "mdc-tab__text-label"
